version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=ad_analytics
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_DB=ad_analytics
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - clickhouse
      - redis

  mock-data-generator:
    build:
      context: .
      dockerfile: docker/generator.Dockerfile
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_DB=ad_analytics
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - MOCK_DATA_INTERVAL_SECONDS=60
    depends_on:
      - clickhouse

  etl-worker:
    build:
      context: .
      dockerfile: docker/etl.Dockerfile
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_DB=ad_analytics
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - clickhouse
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  clickhouse-data: